version: '2.1'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - /controller/src/main/resources/script/init:/docker-entrypoint-initdb.d
    networks:
      - backend

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres:

