version: "3.9"

services:
  app:
    #restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

  react-app:
    build:
      context: ../../react/react-frontend-task
      dockerfile: ../../react/react-frontend-task/Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - app
    networks:
      - frontend


  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
#      - ./pg-sqript:/docker-entrypoint-initdb.d
     - ./db-sqripts:/docker-entrypoint-initdb.d
    networks:
      - backend
networks:
  backend:
  frontend:

volumes:
  postgres:

