version: "3.9"

services:
  app:
    #restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pg-scripts:/docker-entrypoint-initdb.d
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
networks:
  backend:

volumes:
  postgres:

