spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/spring-security'
    username: root
    password: 1243
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  mail:
    protocol: smtps
    host: smtp.mail.ru
    port: 465
    username: test_my_sender
    password: 'sJ1Pf3BiSRjFy8h29ftR'

jwt:
  token:
    secret: jwtapp
    expired: 3600000
