spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://db:5432/spring-security
    url: jdbc:postgresql://aaaaaaaaaaaaaa.cnov1ap5fy4d.eu-west-2.rds.amazonaws.com/postgres
    username: root
    password: 12431243
    initialization-mode: ALWAYS
  #sql.init.mode: always
  jpa:
   #defer-datasource-initialization: true
   show-sql: true
   generate-ddl: false
   hibernate:
     ddl-auto: none
  mail:
    protocol: smtps
    host: smtp.mail.ru
    port: 465
    username: test_my_sender
    password: 'VpWXD3mxgBSb2VaGDPmT'

jwt:
  token:
    secret: jwtapp
    expired: 3600000
server:
  port: 8080
