create table "roles"
(
    id   bigserial constraint roles_pkey PRIMARY KEY not null,
    name varchar(64)           not null
);

create table "users"
(
    id                  bigserial constraint users_pkey PRIMARY KEY not null,
    email               varchar(64)           not null unique,
    name                varchar(64),
    surname             varchar(64),
    pass                varchar(256),
    creation_date       timestamp             not null,
    last_update_date    timestamp             not null,
    version             integer               not null,
    ban_date            timestamp,
    is_active           boolean default (false),
    image_url           varchar(255),
    last_visit_date     timestamp,
    activation_token    varchar(255),
    recovery_token      varchar(255),
    token_creation_date timestamp
);

-- create table user_roles
-- (
--     user_id bigserial not null primary key,
--     role_id bigserial not null primary key,
--     CONSTRAINT "FK_user_id" FOREIGN KEY ("user_id")
--         REFERENCES "users" ("id"),
--     CONSTRAINT "FK_role_id" FOREIGN KEY ("role_id")
--         REFERENCES "roles" ("id")
-- );

create table user_roles
(
    user_id bigserial not null
        constraint fk2o0jvgh89lemvvo17cbqvdxaa
            references users,
    role_id bigserial not null
        constraint fkj6m8fwv7oqv74fcehir1a9ffy
            references roles,
    constraint user_roles_pkey
        primary key (user_id, role_id)
);

create table bodies
(
    id   bigint generated by default as identity
        constraint bodies_pkey
            primary key,
    name varchar(32)
        constraint uk_piys9pn5re1gnfnmxb4px7esc
            unique
);

create table body_report
(
    id                     bigint generated by default as identity
        constraint body_report_pkey
            primary key,
    general_comment        varchar(1024),
    general_recommendation varchar(1024),
    mark                   smallint
);

create table car_brands
(
    id   bigint generated by default as identity
        constraint car_brands_pkey
            primary key,
    name varchar(64)
        constraint uk_p3xsas1wlgmbfp3u8bnqemqss
            unique
);

create table car_error
(
    id          bigint generated by default as identity
        constraint car_error_pkey
            primary key,
    description varchar(255) not null,
    name        varchar(255) not null
);

create table car_part_description
(
    id              bigint generated by default as identity
        constraint car_part_description_pkey
            primary key,
    comment         varchar(1024),
    describing_part varchar(32),
    photo_url       varchar(256),
    recommendation  varchar(1024)
);


create table body_report_descriptions
(
    body_report_id  bigint not null
        constraint fkgd6wxolow4dj1592s8m3ntotv
            references body_report,
    descriptions_id bigint not null
        constraint uk_du626c11jtew4t6up2sagq9cp
            unique
        constraint fk57wn2vo67machif60mdub4ffe
            references car_part_description,
    constraint body_report_descriptions_pkey
        primary key (body_report_id, descriptions_id)
);

create table currency_type
(
    id                   bigint generated by default as identity
        constraint currency_type_pkey
            primary key,
    name                 varchar(32)
        constraint uk_itv2jxh3yu5uk8cj9g0kkojl3
            unique,
    rate_relative_dollar double precision
);

create table drives
(
    id   bigint generated by default as identity
        constraint drives_pkey
            primary key,
    name varchar(32)
        constraint uk_4m04kwio4fksg6ex58l92p8ug
            unique
);

create table transmissions
(
    id   bigint generated by default as identity
        constraint transmissions_pkey
            primary key,
    name varchar(32)
        constraint uk_e81gji5meo4xcg6tkvfl6rm05
            unique
);

create table transmission_report
(
    id bigint generated by default as identity
        constraint transmission_report_pkey
            primary key
);

create table note_on_work
(
    id          bigint generated by default as identity
        constraint note_on_work_pkey
            primary key,
    description varchar(512),
    name        varchar(64)
);

create table order_statuses
(
    id   bigint generated by default as identity
        constraint order_statuses_pkey
            primary key,
    name varchar(64)
        constraint uk_p14tnvp6d460yt9akmq14bigx
            unique
);

create table transmission_report_note_on_work_set
(
    transmission_report_id bigint not null
        constraint fk7e7bqc6ulylwuwx0iog38qs9u
            references transmission_report,
    note_on_work_set_id    bigint not null
        constraint uk_smtiytyp5j7k4bepf6mfxu05m
            unique
        constraint fkgbxyo8cc55l4clx3u7rq2amn6
            references note_on_work,
    constraint transmission_report_note_on_work_set_pkey
        primary key (transmission_report_id, note_on_work_set_id)
);

create table electrical_equipment_report
(
    id                     bigint generated by default as identity
        constraint electrical_equipment_report_pkey
            primary key,
    general_comment        varchar(1024),
    general_recommendation varchar(1024),
    mark                   smallint
);

create table electrical_equipment_report_descriptions
(
    electrical_equipment_report_id bigint not null
        constraint fk12jiluv8j2cslaftbejm817kb
            references electrical_equipment_report,
    descriptions_id                bigint not null
        constraint uk_k4bxf5ogqfp2c4ltc2u8v2hod
            unique
        constraint fknfbhav8pws6ms5k83uudw5p5h
            references car_part_description,
    constraint electrical_equipment_report_descriptions_pkey
        primary key (electrical_equipment_report_id, descriptions_id)
);

create table engine_report
(
    id       bigint generated by default as identity
        constraint engine_report_pkey
            primary key,
    oil_pure varchar(32)
);

create table engine_report_note_on_work_set
(
    engine_report_id    bigint not null
        constraint fkk74y2x5yhs83qwarjvq9jitq2
            references engine_report,
    note_on_work_set_id bigint not null
        constraint uk_nixvyum8xihd4b4ktiqudwlv0
            unique
        constraint fk9we5u2x25tq0nehkfq8sfwh1t
            references note_on_work,
    constraint engine_report_note_on_work_set_pkey
        primary key (engine_report_id, note_on_work_set_id)
);

create table engines
(
    id   bigint generated by default as identity
        constraint engines_pkey
            primary key,
    name varchar(32)
        constraint uk_g0legd0ct1utt6qndfh5jdsmc
            unique
);



create table reports
(
    id               bigint generated by default as identity
        constraint reports_pkey
            primary key,
    creation_date    timestamp not null,
    last_update_date timestamp not null,
    version          integer   not null
);


create table pendant_report
(
    id                     bigint generated by default as identity
        constraint pendant_report_pkey
            primary key,
    general_comment        varchar(1024),
    general_recommendation varchar(1024),
    mark                   smallint
);

create table salon_report
(
    id                     bigint generated by default as identity
        constraint salon_report_pkey
            primary key,
    general_comment        varchar(1024),
    general_recommendation varchar(1024),
    mark                   smallint
);

create table inspection_report
(
    auction_value                  double precision,
    cost_value                     double precision,
    engine_volume                  double precision,
    inspection_date                date,
    is_mileage_real                boolean,
    is_vin_number_real             boolean,
    mileage                        integer,
    model                          varchar(255),
    vin_number                     varchar(255),
    year                           integer,
    id                             bigint not null
        constraint inspection_report_pkey
            primary key
        constraint fkr0lvwpvghetghj8syn1ttpib2
            references reports,
    body                           bigint
        constraint fk7ucashcn2344xuxu4eib50l53
            references bodies,
    body_report_id                 bigint
        constraint fkr30dee1w4k4snl5gcb20r6akh
            references body_report,
    car_brand                      bigint
        constraint fkkxmbxehgwk3hemx62qwoxono8
            references car_brands,
    currency_type_id               bigint
        constraint fkpv0i1uvwh5rfocvt5g2ha05fm
            references currency_type,
    drive                          bigint
        constraint fkgagio35grfupftg1wc1md8ykg
            references drives,
    electrical_equipment_report_id bigint
        constraint fk6llmt5b9jdfsgmk2kb8fuee9h
            references electrical_equipment_report,
    engine                         bigint
        constraint fk9xnkxj2if8fmkxsas3710tvon
            references engines,
    engine_report_id               bigint
        constraint fk4plchx0qj0ihuiv291fj74n88
            references engine_report,
    pendant_report_id              bigint
        constraint fk9qsin1gl9g9h4no80mcxemtrg
            references pendant_report,
    salon_report_id                bigint
        constraint fkg7imntga3roxuplhfvp77ehad
            references salon_report,
    transmission                   bigint
        constraint fkhc9l0nm6osegpj55giaefypo8
            references transmissions,
    transmission_report_id         bigint
        constraint fkpv8x6t7moufejihgatks93i0
            references transmission_report
);


create table inspect_report_car_errors
(
    report_id bigint not null
        constraint fk4hsmj7nsyc6ar7eqgijr12utu
            references inspection_report,
    error_id  bigint not null
        constraint fkbofrqdsl5o9w51w24tvbfpaxm
            references car_error,
    constraint inspect_report_car_errors_pkey
        primary key (report_id, error_id)
);

create table orders
(
    id               bigint generated by default as identity
        constraint orders_pkey
            primary key,
    creation_date    timestamp not null,
    last_update_date timestamp not null,
    version          integer   not null,
    auto_picker      bigint
        constraint fk7y1tpyk93k8i8b5veoour3rum
            references users,
    creator          bigint
        constraint fkqva2c6q8ug27inla0tu1h0nej
            references users,
    order_status     bigint
        constraint fk54qn2rttxg5s7o4w5h5lrv9x6
            references order_statuses,
    report_id        bigint
        constraint fkmf98n8ktconiih4l3b02tvbdh
            references reports
);

create table inspection_orders
(
    additional_info      varchar(512),
    auto_url             varchar(255) not null,
    id                   bigint       not null
        constraint inspection_orders_pkey
            primary key
        constraint fkd49rw0mgff8dywgm7i88c7tu2
            references orders,
    inspection_report_id bigint
);

create table pendant_report_descriptions
(
    pendant_report_id bigint not null
        constraint fk9v6j2hji7hq7pxatfm2pl7yr1
            references pendant_report,
    descriptions_id   bigint not null
        constraint uk_eb09nceta9ul5ver3gkp6n8xc
            unique
        constraint fkeydkvw4bpke8erf6tvg45r1gm
            references car_part_description,
    constraint pendant_report_descriptions_pkey
        primary key (pendant_report_id, descriptions_id)
);

create table salon_report_descriptions
(
    salon_report_id bigint not null
        constraint fkgc5cuir1fl0ul83ldnjs6le24
            references salon_report,
    descriptions_id bigint not null
        constraint uk_spgbwcrr0lrl2mijhb56v936h
            unique
        constraint fkmsgt1q92ge35pmujc43bgbf99
            references car_part_description,
    constraint salon_report_descriptions_pkey
        primary key (salon_report_id, descriptions_id)
);


create table selection_orders
(
    additional_info     varchar(512),
    max_engine_volume   double precision,
    mileage             integer,
    min_engine_volume   double precision,
    min_year            integer,
    range_from          double precision,
    range_to            double precision,
    id                  bigint not null
        constraint selection_orders_pkey
            primary key
        constraint fkhe1y7tv5ytn60pl1yphqbk65s
            references orders,
    currency_type_id    bigint
        constraint fk3b0oqx1ceg4mjkv8iihk6kink
            references currency_type,
    currency_range_from double precision,
    currency_range_to   double precision
);

create table selec_orders_body
(
    order_id bigint not null
        constraint fke9m3nuwj49kv22twerpkofyh5
            references selection_orders,
    body_id  bigint not null
        constraint fkgvncx0gl2hf1w4ukd7b5eiqht
            references bodies,
    constraint selec_orders_body_pkey
        primary key (order_id, body_id)
);

create table selec_orders_car_brands
(
    order_id bigint not null
        constraint fk345qvx90dmnggvpu5g19x5lrk
            references selection_orders,
    brand_id bigint not null
        constraint fk2opa5rx47ry74xor4g2sa4tv9
            references car_brands,
    constraint selec_orders_car_brands_pkey
        primary key (order_id, brand_id)
);

create table selec_orders_drives
(
    order_id bigint not null
        constraint fkpdddgt7asyl105l1ymwqgr4xd
            references selection_orders,
    drive_id bigint not null
        constraint fk59n6cdm6o2tso3n71u0rc60bh
            references drives,
    constraint selec_orders_drives_pkey
        primary key (order_id, drive_id)
);

create table selec_orders_engines
(
    order_id  bigint not null
        constraint fkm3l7n797wuyjp9hcv7d9a5ucd
            references selection_orders,
    engine_id bigint not null
        constraint fkdul2dg7qgjkjkard7gvkgncx6
            references engines,
    constraint selec_orders_engines_pkey
        primary key (order_id, engine_id)
);

create table selec_orders_transmissions
(
    order_id        bigint not null
        constraint fkqk5sp1uct5chbtw18ngqtucnr
            references selection_orders,
    transmission_id bigint not null
        constraint fkch880omqqbt84ej24gaxumbf4
            references transmissions,
    constraint selec_orders_transmissions_pkey
        primary key (order_id, transmission_id)
);

create table selected_car
(
    id      bigint generated by default as identity
        constraint selected_car_pkey
            primary key,
    car_url varchar(255),
    comment varchar(1024)
);


create table selection_report
(
    id bigint not null
        constraint selection_report_pkey
            primary key
        constraint fk3x63d61nkvptc9g45x47bxek
            references reports
);

create table selection_report_selected_car_set
(
    selection_report_id bigint not null
        constraint fk8411ab814fvcwvntmd31iyhhp
            references selection_report,
    selected_car_set_id bigint not null
        constraint uk_8esgoemd8ft7ju3ymneiq43pw
            unique
        constraint fk92fkwsvy31x7k5rsr2vxhs2jq
            references selected_car,
    constraint selection_report_selected_car_set_pkey
        primary key (selection_report_id, selected_car_set_id)
);





